const ActionTypes = {
  GET_DAY_REVENUE: 'GET_DAY_REVENUE',
  GET_WEEK_REVENUE: 'GET_WEEK_REVENUE',
  GET_MONTH_REVENUE: 'GET_MONTH_REVENUE',
  GET_TOP_DAY_TUTOR: 'GET_TOP_DAY_TUTOR',
  GET_TOP_WEEK_TUTOR: 'GET_TOP_WEEK_TUTOR',
  GET_TOP_MONTH_TUTOR: 'GET_TOP_MONTH_TUTOR',
  GET_TODAY_REVENUE: ' GET_TODAY_REVENUE',
};

export default ActionTypes;
