export default [
  {
    id: 2,
    username: "anvh",
    password: "123",
    email: "anvh@gmail.com",
    address: "TPHCM",
    district: "Quận 7",
    city: "TP.HCM",
    name: "An",
    phone: "123456",
    dob: "1998-10-21T00:00:00.000Z",
    card_id: "123456",
    gender: "Nam",
    role: 1,
    avatar: "",
    skill_tags: "[\"English\"]",
    price_per_hour: 30000,
    num_stars: 3,
    num_rate: 3,
    intro_desc: "Toi day Toan, Ly va Hoa",
    degree: null,
    account_status: null
},
{
    id: 25,
    username: "dungnq",
    password: "123456",
    email: "quocdung1612@gmail.com",
    address: "336/1 Phạm Hữu Lầu",
    district: "Quận 8",
    city: "TP.HCM",
    name: "Dũng",
    phone: "0965577030",
    dob: "1998-12-16T00:00:00.000Z",
    card_id: "123456789",
    gender: "Nam",
    role: 2,
    avatar: "http://localhost:55210/public/default-avatar",
    skill_tags: null,
    price_per_hour: null,
    num_stars: null,
    num_rate: null,
    intro_desc: null,
    degree: null,
    account_status: null
},
{
    id: 35,
    username: "anvh2",
    password: "123",
    email: "anvo.ht209@gmail.com",
    address: "227 Phạm Hùng",
    district: "Quận 8",
    city: "TP.HCM",
    name: "Vo Hoang An",
    phone: "123456",
    dob: "1998-10-21T00:00:00.000Z",
    card_id: "1234567",
    gender: "Nam",
    role: 1,
    avatar: "http://localhost:55210/public/default-avatar",
    skill_tags: "[\"English\"]",
    price_per_hour: 20000,
    num_stars: 4,
    num_rate: 1,
    intro_desc: "Toi day Toan, Ly va Hoa",
    degree: "Dai hoc KHTN",
    account_status: 1
},
{
    id: 48,
    username: "facebook_1001782109929",
    password: null,
    email: null,
    address: null,
    district: "Quận Bình Thạnh",
    city: "TP.HCM",
    name: "Kassie",
    phone: null,
    dob: null,
    card_id: null,
    gender: null,
    role: 0,
    avatar: null,
    skill_tags: null,
    price_per_hour: null,
    num_stars: null,
    num_rate: null,
    intro_desc: "Toi day Toan, Ly va Hoa",
    degree: null,
    account_status: 1
},
{
    id: 49,
    username: "anvh3",
    password: "123",
    email: "anvo.ht209@gmail.com",
    address: "TPHCM",
    district: "Quận 2",
    city: "TP.HCM",
    name: "An",
    phone: "123456",
    dob: "1998-10-21T00:00:00.000Z",
    card_id: "1234567",
    gender: "Nam",
    role: 2,
    avatar: "http://localhost:55210/public/default-avatar",
    skill_tags: null,
    price_per_hour: null,
    num_stars: null,
    num_rate: null,
    intro_desc: null,
    degree: null,
    account_status: 1
},
{
    id: 50,
    username: "anvh4",
    password: "123",
    email: "anvo.ht209@gmail.com",
    address: "TPHCM",
    district: "Quận 8",
    city: "TP.HCM",
    name: "An",
    phone: "123456",
    dob: "1998-10-21T00:00:00.000Z",
    card_id: "1234567",
    gender: "Nam",
    role: 1,
    avatar: "http://localhost:55210/public/default-avatar",
    skill_tags: "[\"English\"]",
    price_per_hour: 100000,
    num_stars: 3,
    num_rate: 4,
    intro_desc: "Toi day Toan, Ly va Hoa",
    degree: null,
    account_status: 1
},
{
    id: 51,
    username: "anvh5",
    password: "123",
    email: "anvo.ht209@gmail.com",
    address: "TPHCM",
    district: "Quận 7",
    city: "TP.HCM",
    name: "An",
    phone: "123456",
    dob: "1998-10-21T00:00:00.000Z",
    card_id: "1234567",
    gender: "Nam",
    role: 1,
    avatar: "http://localhost:55210/public/default-avatar",
    skill_tags: "[\"English\"]",
    price_per_hour: 80000,
    num_stars: 4,
    num_rate: 3,
    intro_desc: "Toi day Toan, Ly va Hoa",
    degree: null,
    account_status: 1
}
];
